name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: pre-commit
        run: pre-commit run -a
      - name: pytest
        env:
          PASSWORD: "ci-test-password"
          SECRET_KEY: "ci-test-secret"
        run: pytest -q
